services:
    package:
        build:
            context: .
            target: php
            args:
                COMPOSER_VERSION: "2.3"
                PHP_VERSION: "8.0"
        command: ["composer", "update", "--no-interaction"]
        volumes:
            - ./:/package:delegate
